version: '2'

services:
  redis:
    image: 'redis:latest'
    command: redis-server
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "osp_api.app:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/osp_api'
    ports:
      - '8000:8000'
    links:
        - redis

  celery:
    build: .
    command: celery worker -l info -A osp_api.tasks.celery --loglevel=debug
    volumes:
      - '.:/osp_api'
    links:
        - redis

volumes:
  redis:

